
query FilterPermissions($filter: FilterPermissionsInputDto!, $pagination: PaginationInputDto!) {
  permissions: filterPermissions(filter: $filter, pagination: $pagination) {
    ...FullPaginationPermissionsOutputDto
  }
}
